package com.bwie.entity;

/**  
* <p>Title: Address.java</p>  
* <p>Description:Java Bean </p>  
* <p>Copyright: Copyright (c) 2018</p>  
* <p>Company: www.Resource.com</p>  
*/  
public class Address {

	// 地址的Id
    private Integer aid;

    // 地址名称
    private String name;
    
    // 地址的父Id
    private Integer pid;

    
    public Integer getAid() {
        return aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_address.aid
     *
     * @param aid the value for t_address.aid
     *
     * @mbggenerated Fri Mar 30 19:07:51 GMT+08:00 2018
     */
    public void setAid(Integer aid) {
        this.aid = aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_address.name
     *
     * @return the value of t_address.name
     *
     * @mbggenerated Fri Mar 30 19:07:51 GMT+08:00 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_address.name
     *
     * @param name the value for t_address.name
     *
     * @mbggenerated Fri Mar 30 19:07:51 GMT+08:00 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_address.pid
     *
     * @return the value of t_address.pid
     *
     * @mbggenerated Fri Mar 30 19:07:51 GMT+08:00 2018
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_address.pid
     *
     * @param pid the value for t_address.pid
     *
     * @mbggenerated Fri Mar 30 19:07:51 GMT+08:00 2018
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

	@Override
	public String toString() {
		return "Address [aid=" + aid + ", name=" + name + ", pid=" + pid + "]";
	}
    
}