package com.bwie.entity;

public class ApplyType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_reimbursement_name.reimid
     *
     * @mbggenerated Wed Apr 11 09:21:03 GMT+08:00 2018
     */
    private Integer reimid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_reimbursement_name.reiminame
     *
     * @mbggenerated Wed Apr 11 09:21:03 GMT+08:00 2018
     */
    private String reiminame;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_reimbursement_name.reimid
     *
     * @return the value of t_reimbursement_name.reimid
     *
     * @mbggenerated Wed Apr 11 09:21:03 GMT+08:00 2018
     */
    public Integer getReimid() {
        return reimid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_reimbursement_name.reimid
     *
     * @param reimid the value for t_reimbursement_name.reimid
     *
     * @mbggenerated Wed Apr 11 09:21:03 GMT+08:00 2018
     */
    public void setReimid(Integer reimid) {
        this.reimid = reimid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_reimbursement_name.reiminame
     *
     * @return the value of t_reimbursement_name.reiminame
     *
     * @mbggenerated Wed Apr 11 09:21:03 GMT+08:00 2018
     */
    public String getReiminame() {
        return reiminame;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_reimbursement_name.reiminame
     *
     * @param reiminame the value for t_reimbursement_name.reiminame
     *
     * @mbggenerated Wed Apr 11 09:21:03 GMT+08:00 2018
     */
    public void setReiminame(String reiminame) {
        this.reiminame = reiminame;
    }
}