package com.bwie.entity;

public class Reimbursement {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_reimbursement.id
     *
     * @mbggenerated Tue Apr 10 15:19:25 GMT+08:00 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_reimbursement.reiname
     *
     * @mbggenerated Tue Apr 10 15:19:25 GMT+08:00 2018
     */
    private String reiname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_reimbursement.reidate
     *
     * @mbggenerated Tue Apr 10 15:19:25 GMT+08:00 2018
     */
    private String reidate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_reimbursement.reimoney
     *
     * @mbggenerated Tue Apr 10 15:19:25 GMT+08:00 2018
     */
    private Integer reimoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_reimbursement.reistate
     *
     * @mbggenerated Tue Apr 10 15:19:25 GMT+08:00 2018
     */
    private Integer reistate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_reimbursement.uid
     *
     * @mbggenerated Tue Apr 10 15:19:25 GMT+08:00 2018
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_reimbursement.rid
     *
     * @mbggenerated Tue Apr 10 15:19:25 GMT+08:00 2018
     */
    private Integer rid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_reimbursement.id
     *
     * @return the value of t_reimbursement.id
     *
     * @mbggenerated Tue Apr 10 15:19:25 GMT+08:00 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_reimbursement.id
     *
     * @param id the value for t_reimbursement.id
     *
     * @mbggenerated Tue Apr 10 15:19:25 GMT+08:00 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_reimbursement.reiname
     *
     * @return the value of t_reimbursement.reiname
     *
     * @mbggenerated Tue Apr 10 15:19:25 GMT+08:00 2018
     */
    public String getReiname() {
        return reiname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_reimbursement.reiname
     *
     * @param reiname the value for t_reimbursement.reiname
     *
     * @mbggenerated Tue Apr 10 15:19:25 GMT+08:00 2018
     */
    public void setReiname(String reiname) {
        this.reiname = reiname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_reimbursement.reidate
     *
     * @return the value of t_reimbursement.reidate
     *
     * @mbggenerated Tue Apr 10 15:19:25 GMT+08:00 2018
     */
    public String getReidate() {
        return reidate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_reimbursement.reidate
     *
     * @param reidate the value for t_reimbursement.reidate
     *
     * @mbggenerated Tue Apr 10 15:19:25 GMT+08:00 2018
     */
    public void setReidate(String reidate) {
        this.reidate = reidate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_reimbursement.reimoney
     *
     * @return the value of t_reimbursement.reimoney
     *
     * @mbggenerated Tue Apr 10 15:19:25 GMT+08:00 2018
     */
    public Integer getReimoney() {
        return reimoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_reimbursement.reimoney
     *
     * @param reimoney the value for t_reimbursement.reimoney
     *
     * @mbggenerated Tue Apr 10 15:19:25 GMT+08:00 2018
     */
    public void setReimoney(Integer reimoney) {
        this.reimoney = reimoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_reimbursement.reistate
     *
     * @return the value of t_reimbursement.reistate
     *
     * @mbggenerated Tue Apr 10 15:19:25 GMT+08:00 2018
     */
    public Integer getReistate() {
        return reistate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_reimbursement.reistate
     *
     * @param reistate the value for t_reimbursement.reistate
     *
     * @mbggenerated Tue Apr 10 15:19:25 GMT+08:00 2018
     */
    public void setReistate(Integer reistate) {
        this.reistate = reistate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_reimbursement.uid
     *
     * @return the value of t_reimbursement.uid
     *
     * @mbggenerated Tue Apr 10 15:19:25 GMT+08:00 2018
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_reimbursement.uid
     *
     * @param uid the value for t_reimbursement.uid
     *
     * @mbggenerated Tue Apr 10 15:19:25 GMT+08:00 2018
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_reimbursement.rid
     *
     * @return the value of t_reimbursement.rid
     *
     * @mbggenerated Tue Apr 10 15:19:25 GMT+08:00 2018
     */
    public Integer getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_reimbursement.rid
     *
     * @param rid the value for t_reimbursement.rid
     *
     * @mbggenerated Tue Apr 10 15:19:25 GMT+08:00 2018
     */
    public void setRid(Integer rid) {
        this.rid = rid;
    }
}