package com.bwie.entity;

public class Resource {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_privillege.pid
     *
     * @mbggenerated Mon Apr 02 11:29:22 GMT+08:00 2018
     */
    private Integer pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_privillege.url
     *
     * @mbggenerated Mon Apr 02 11:29:22 GMT+08:00 2018
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_privillege.pname
     *
     * @mbggenerated Mon Apr 02 11:29:22 GMT+08:00 2018
     */
    private String pname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_privillege.pid
     *
     * @return the value of t_privillege.pid
     *
     * @mbggenerated Mon Apr 02 11:29:22 GMT+08:00 2018
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_privillege.pid
     *
     * @param pid the value for t_privillege.pid
     *
     * @mbggenerated Mon Apr 02 11:29:22 GMT+08:00 2018
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_privillege.url
     *
     * @return the value of t_privillege.url
     *
     * @mbggenerated Mon Apr 02 11:29:22 GMT+08:00 2018
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_privillege.url
     *
     * @param url the value for t_privillege.url
     *
     * @mbggenerated Mon Apr 02 11:29:22 GMT+08:00 2018
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_privillege.pname
     *
     * @return the value of t_privillege.pname
     *
     * @mbggenerated Mon Apr 02 11:29:22 GMT+08:00 2018
     */
    public String getPname() {
        return pname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_privillege.pname
     *
     * @param pname the value for t_privillege.pname
     *
     * @mbggenerated Mon Apr 02 11:29:22 GMT+08:00 2018
     */
    public void setPname(String pname) {
        this.pname = pname;
    }
}