package com.bwie.entity;

public class State {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_state.sid
     *
     * @mbggenerated Tue Apr 10 15:19:25 GMT+08:00 2018
     */
    private Integer sid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_state.sname
     *
     * @mbggenerated Tue Apr 10 15:19:25 GMT+08:00 2018
     */
    private String sname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_state.sid
     *
     * @return the value of t_state.sid
     *
     * @mbggenerated Tue Apr 10 15:19:25 GMT+08:00 2018
     */
    public Integer getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_state.sid
     *
     * @param sid the value for t_state.sid
     *
     * @mbggenerated Tue Apr 10 15:19:25 GMT+08:00 2018
     */
    public void setSid(Integer sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_state.sname
     *
     * @return the value of t_state.sname
     *
     * @mbggenerated Tue Apr 10 15:19:25 GMT+08:00 2018
     */
    public String getSname() {
        return sname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_state.sname
     *
     * @param sname the value for t_state.sname
     *
     * @mbggenerated Tue Apr 10 15:19:25 GMT+08:00 2018
     */
    public void setSname(String sname) {
        this.sname = sname;
    }
}