package com.bwie.entity;
/**
 *
 * 
 */
public class User {

	// ÓÃ»§Id
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.username
     *
     * @mbggenerated Thu Mar 29 20:52:40 GMT+08:00 2018
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.password
     *
     * @mbggenerated Thu Mar 29 20:52:40 GMT+08:00 2018
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.uname
     *
     * @mbggenerated Thu Mar 29 20:52:40 GMT+08:00 2018
     */
    private String uname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.age
     *
     * @mbggenerated Thu Mar 29 20:52:40 GMT+08:00 2018
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.phone
     *
     * @mbggenerated Thu Mar 29 20:52:40 GMT+08:00 2018
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.address
     *
     * @mbggenerated Thu Mar 29 20:52:40 GMT+08:00 2018
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.did
     *
     * @mbggenerated Thu Mar 29 20:52:40 GMT+08:00 2018
     */
    private Integer did;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.uid
     *
     * @return the value of t_users.uid
     *
     * @mbggenerated Thu Mar 29 20:52:40 GMT+08:00 2018
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.uid
     *
     * @param uid the value for t_users.uid
     *
     * @mbggenerated Thu Mar 29 20:52:40 GMT+08:00 2018
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.username
     *
     * @return the value of t_users.username
     *
     * @mbggenerated Thu Mar 29 20:52:40 GMT+08:00 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.username
     *
     * @param username the value for t_users.username
     *
     * @mbggenerated Thu Mar 29 20:52:40 GMT+08:00 2018
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.password
     *
     * @return the value of t_users.password
     *
     * @mbggenerated Thu Mar 29 20:52:40 GMT+08:00 2018
     */
    public String getPassword() {
        return password;
    }

    @Override
	public String toString() {
		return "User [uid=" + uid + ", username=" + username + ", password="
				+ password + ", uname=" + uname + ", age=" + age + ", phone="
				+ phone + ", address=" + address + ", did=" + did + "]";
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.password
     *
     * @param password the value for t_users.password
     *
     * @mbggenerated Thu Mar 29 20:52:40 GMT+08:00 2018
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.uname
     *
     * @return the value of t_users.uname
     *
     * @mbggenerated Thu Mar 29 20:52:40 GMT+08:00 2018
     */
    public String getUname() {
        return uname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.uname
     *
     * @param uname the value for t_users.uname
     *
     * @mbggenerated Thu Mar 29 20:52:40 GMT+08:00 2018
     */
    public void setUname(String uname) {
        this.uname = uname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.age
     *
     * @return the value of t_users.age
     *
     * @mbggenerated Thu Mar 29 20:52:40 GMT+08:00 2018
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.age
     *
     * @param age the value for t_users.age
     *
     * @mbggenerated Thu Mar 29 20:52:40 GMT+08:00 2018
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.phone
     *
     * @return the value of t_users.phone
     *
     * @mbggenerated Thu Mar 29 20:52:40 GMT+08:00 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.phone
     *
     * @param phone the value for t_users.phone
     *
     * @mbggenerated Thu Mar 29 20:52:40 GMT+08:00 2018
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.address
     *
     * @return the value of t_users.address
     *
     * @mbggenerated Thu Mar 29 20:52:40 GMT+08:00 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.address
     *
     * @param address the value for t_users.address
     *
     * @mbggenerated Thu Mar 29 20:52:40 GMT+08:00 2018
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.did
     *
     * @return the value of t_users.did
     *
     * @mbggenerated Thu Mar 29 20:52:40 GMT+08:00 2018
     */
    public Integer getDid() {
        return did;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.did
     *
     * @param did the value for t_users.did
     *
     * @mbggenerated Thu Mar 29 20:52:40 GMT+08:00 2018
     */
    public void setDid(Integer did) {
        this.did = did;
    }
}